sudo: false
services:
  - redis-server
language: node_js
node_js:
  - "8.3.0"
 
before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"

script:
  - meteor --once test-packages --driver-package meteortesting:mocha ./